import Head from 'next/head'
import { css, } from '@emotion/react';
import styled from '@emotion/styled';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bee See</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Header>Hello BeeSee</Header>
      </Section>

    </>
  )
}

const Section = styled.section`
padding-bottom: 34px;
background: #FFFFFF;
`;
const Header = styled.p`
color: red;
font-size: 32px;
line-height: 48px;
font-weight: 600;
text-align: center;
`;
